### ISSUE TITLE
issingSchemaError

### ISSUE THREAD

**Issue by YounggilLee** [YounggilLee/Email_Survey_System#4]
issingSchemaError: Schema hasn't been registered for model "users".
Use mongoose.model(name, schema)
    at MongooseError.MissingSchemaError (/Users/gil/WorkSpace/Email_Survey_System/server/node_modules/mongoose/lib/error/missingSchema.js:20:11)
    at Mongoose.model (/Users/gil/WorkSpace/Email_Survey_System/server/node_modules/mongoose/lib/index.js:391:13)

**Comment by YounggilLee** [comment]
changing the order in index.js

require('./services/passport');
require('./models/User');

==> 
require('./models/User');
require('./services/passport');
