### ISSUE TITLE
Issue - After refactoring from chaining(.then) to async

### ISSUE THREAD

**Issue by YounggilLee** [YounggilLee/Email_Survey_System#5]
In server side......

async (accessToken, refreshToken, profile, done) => {
[0]           ^
[0]
[0] SyntaxError: Unexpected token (
[0]     at createScript (vm.js:56:10)
[0]     at Object.runInThisContext (vm.js:97:10)
[0]     at Module._compile (module.js:542:28)
[0]     at Object.Module._extensions..js (module.js:579:10)
[0]     at Module.load (module.js:487:32)
[0]     at tryModuleLoad (module.js:446:12)
[0]     at Function.Module._load (module.js:438:3)
[0]     at Module.require (module.js:497:17)
[0]     at require (internal/module.js:20:19)
[0]     at Object.<anonymous> (/Users/gil/Work

**Comment by YounggilLee** [comment]
update node version from 6. to over 8.
async is not working under version 8
--------------How to update the version of node---
sudo npm cache clean -f
sudo npm install -g n
sudo n stable
